[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = ""
authors = ["Satoaki Ishihara"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.35.10"
load-dotenv = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
